INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('23', 'ODP', 'Ocean Drilling Program', 'Texas A and M University', '1000 Discovery Drive', 'College Station, TX 77845', 'USA', 'John Firth 1 979 845-0507', 'Phil Rumford 1 979 845-8490', null, 'rumford@iodp.tamu.edu', 'http://iodp.tamu.edu/curation/', null, null, '<p><a href="http://iodp.tamu.edu/curation/">Integrated Ocean Drilling Program (IODP) Permanent Archives</a><br>(http://iodp.tamu.edu/curation/)<br><br>International Ocean Discovery Program<br>Bremen repository, <br>Gulf Coast repository,<br>and Kochi Core Center <br><br><a href="http://iodp.tamu.edu/curation/repositories.html">Core location and Contact information</a></p><br><br><cite>Cite as: International Ocean Discovery Program (IODP): Archive of geosample data and information from scientific ocean drilling. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V57M05XN">doi:10.7289/V57M05XN</a> [date of access]</cite>', 20211221, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('15', 'DSDP', 'Deep Sea Drilling Project', 'Texas A and M University', '1000 Discovery Drive', 'College Station, TX 77845', 'USA', 'John Firth 1 979 845-0507', 'Phil Rumford 1 979 845-8490', null, 'rumford@iodp.tamu.edu', 'http://iodp.tamu.edu/curation/', null, null, '<p><a href="http://iodp.tamu.edu/curation/">Deep Sea Drilling Project (DSDP) Permanent Archives</a><br>(http://iodp.tamu.edu/curation/)<br><br>International Ocean Discovery Program<br>Bremen Core Repository, <br>Gulf Coast Repository,<br>and Kochi Core Center <br><br><a href="http://iodp.tamu.edu/curation/repositories.html">Core location and Contact information</a></p><br><br><cite>Cite as: International Ocean Discovery Program (IODP): Archive of geosample data and information from scientific ocean drilling. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V57M05XN">doi:10.7289/V57M05XN</a> [date of access]</cite>', 20220224, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('21', 'NMNH', 'National Museum of Natural History', 'Dept of Paleobiology, Smithsonian Institution', 'P.O. Box 37012, MRC-121', 'Washington, D.C. 20013-7012', 'USA', 'Kathy Hollis 1 202 633-1357', null, null, 'HollisK@si.edu', 'http://collections.nmnh.si.edu/search/', null, null, '<p align="center"><a href="http://www.nmnh.si.edu/paleo/index.html">Department of Paleobiology</a><br>National Museum of Natural History (NMNH) <br>Smithsonian Institution <br>P.O. Box 37012, MRC-121 <br>Washington, D.C. 20013-7012 <br> <br>Kathy Hollis (collections manager) <br>(202)633-1357<br><a href="mailto:HollisK@si.edu">HollisK@si.edu</a> <br>(202)786-2832 (fax) <br> </p> <blockquote>Information provided with the permission of the National Museum of Natural History, <br>Smithsonian Institution, 10th and Constitution Ave. N.W., Washington, DC 20560-0193. <br>(<a href="http://www.nmnh.si.edu/">http://www.nmnh.si.edu/</a>)</blockquote><br><br>
<cite>Cite as: Smithsonian National Museum of Natural History (NMNH)(2001): Archive of information about geosamples curated by NMNH collected during NOAA/NOS and USCGS hydrographic surveys. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5J38QHJ">doi:10.7289/V5J38QHJ</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('19', 'BOSCORF', 'British Ocean Sediment Core Research Facility', 'National Oceanography Centre', 'Empress Dock, European Way', 'Southampton S014 3ZH', 'United Kingdom', 'Suzanne MacLachlan', 'Guy Rothwell 44 2380 596567', null, 'boscorf@noc.ac.uk', 'http://www.boscorf.org', null, null, '
<p><a href="http://www.boscorf.org" target="_top">British Ocean Sediment Core Research Facility (BOSCORF),
<br>National Oceanography Centre, United Kingdom</a><br><http://www.boscorf.org)<p>
<a href="http://www.eu-seased.net/" target="_top">EU-SEASED European Sample Database</a><br><http://www.eu-seased.net/)
<br>Guy Rothwell<br>Suzanne MacLachlan<br>National Oceanography Centre<br>Empress Dock<br>European Way<br>Southampton S014 3ZH<br>
United Kingdom<br>44 2380 596567 (Guy Rothwell)<br>
<a href="mailto"boscorf@noc.ac.uk">boscorf@noc.ac,.uk</a><br>44 2380 596554 (fax)<br>
</p>
<br><br>Cite as: British Ocean Sediment Core Research Facility (BOSCORF): Archive of information about the BOSCORF geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5N014HR" title="external link to resolve DOI">doi:10.7289/V5N014HR</a> [date of access]<br><br>
', 20150925, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('23', 'IODP', 'International Ocean Discovery Program', 'Texas A and M University', '1000 Discovery Drive', 'College Station, TX 77845', 'USA', 'John Firth 1 979 845-0507', 'Phil Rumford 1 979 845-8490', null, 'rumford@iodp.tamu.edu', 'http://iodp.tamu.edu/curation/', null, null, '<p><a href="http://iodp.tamu.edu/curation/">Integrated Ocean Drilling Program (IODP) Permanent Archives</a><br>(http://iodp.tamu.edu/curation/)<br><br>International Ocean Discovery Program<br>Bremen repository, <br>Gulf Coast repository,<br>and Kochi Core Center <br><br><a href="http://iodp.tamu.edu/curation/repositories.html">Core location and Contact information</a></p><br><br><cite>Cite as: International Ocean Discovery Program (IODP): Archive of geosample data and information from scientific ocean drilling. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V57M05XN">doi:10.7289/V57M05XN</a> [date of access]</cite>', 20211221, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('99', 'ECS', 'US Extended Continental Shelf Samples Repository', 'Coastal and Marine Science Center', '384 Woods Hole Rd', 'Woods Hole, MA 02543', 'USA', 'Brian Buczkowski 1 508 457-2361', null, null, 'bbuczkowski@usgs.gov', 'http://www.ngdc.noaa.gov/mgg/ecs/', null, null, '<cite>Cite as: Oregon State University (OSU) Marine Geology Repository (MGR): Archive of OSU geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5TH8JPB">doi:10.7289/V5TH8JPB</a> [date of access]</cite>"', 20151027, 'Y', null);
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('94', 'LacCore', 'National Lacustrine Core Repository', 'University of Minnesota', '500 Pillsbury Drive SE, Room 672', 'Minneapolis, MN 55455', 'USA', 'Anders Noren 1 612 626-7889', 'Kristina Brady ', null, 'brad0311@umn.edu', 'http://lrc.geo.umn.edu/LacCore/laccore.html', null, null, '<p><a href="http://lrc.geo.umn.edu/LacCore/laccore.html">US National Lacustrine Core Repository</a><br>(http://lrc.geo.umn.edu/LacCore/laccore.html)<br>Anders Noren<br>Kristina Brady<br>National Lacustrine Core Repository<br>Department of Geology and Geophysics<br>University of Minnesota<br>500 Pillsbury Drive SE, Room 672<br>Minneapolis, MN USA 55455<br>(612)626-7889<br>(612)626-7750 (fax)<br><a href="mailto:noren021@umn.edu">noren021@umn.edu</a><br><a href="mailto:brad0311@umn.edu">brad0311@umn.edu</a><br></p><br><br>
<cite>Cite as: University of Minnesota National Lacustrine Core Repository (LacCore): Archive of LacCore geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5G73BP3">doi:10.7289/V5G73BP3</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('08', 'SOEST', 'University of Hawaii at Manoa', 'Department of Geology and Geophysics', '1680 East-West Road', 'Honolulu, HI 96822', 'USA', 'Kevin Johnson 1 808 956-3444 (dredges)', 'Jane Schoonmaker 1 808 956-6827 (cores)', null, 'kjohnso2@hawaii.edu', 'http://www.soest.hawaii.edu/', null, null, '<p><a href="http://www.soest.hawaii.edu/">School of Ocean and Earth Science and Technology, University of Hawaii</a><br>(http://www.soest.hawaii.edu/)<br><br>Kevin Johnson<br>Dredge Curator<br>University of Hawaii at Manoa<br>Department of Geology and Geophysics<br>1680 East-West Road<br>Honolulu, HI 96822<br>(808)956-3444<br><a href="mailto:kjohnso2@hawaii.edu">kjohnso2@hawaii.edu</a></p><br><br>
<cite>Cite as: University of Hawaii at Manoa, School of Ocean and Earth Science and Technology (SOEST): Archive of SOEST geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V50P0X05">doi:10.7289/V50P0X05</a> [date of access].</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('27', 'USC', 'University of Southern California', 'Department of Earth Sciences', 'Zumberge, 3651 Tousdale Pkwy', 'Los Angeles, CA 90089-0740', 'USA', 'Curator 1 213 740-6106', null, null, 'earthsci@usc.edu', 'http://cwis.usc.edu/dept/earth/', null, null, '<p><a href="http://cwis.usc.edu/dept/earth/">University of Southern California, Department of Earth Sciences</a><br>(http://cwis.usc.edu/dept/earth/)<br>Curator<br>University of Southern California<br>Department of Geological Sciences<br>Zumberge Hall of Science<br>3651 Trousdale Pkwy<br>Los Angeles, CA 90089-0740<br>(213)740-6106<br>(213)740-8801(fax)<br><a href="mailto:earthsci@usc.edu">earthsci@usc.edu</a><br></p><br><br>
<cite>Cite as: University of Southern California (USC) Department of Earth Sciences: Archive of information about the USC geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V58P5XH8">doi:10.7289/V58P5XH8</a> [date of access]
</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('03', 'AOML', 'NOAA-Atlantic Oceanographic and Meteorol. Lab', 'NOAA-AOML', '4301 Rickenbacker Causeway', 'Miami, FL 33149', 'USA', 'Charles Featherstone 1 305 361-4401', 'The AOML core repository is closed', 'no samples are available', 'charles.featherstone@noaa.gov', 'http://www.aoml.noaa.gov/', null, null, '<p><a href="http://www.aoml.noaa.gov/" target="_top">Atlantic Oceanographic and Meteorological Laboratories (AOML)</a>
<br>(http://www.aoml.noaa.gov/)
<br>Charles Featherstone
<br>NOAA - Atlantic Oceanographic and Meteorological Laboratories
<br>4301 Rickenbacker Causeway<br>Miami, FL  33149
<br>(305)361-4401
<br>(305)361-4392 (fax)
<br><a href="mailto:charles.featherstone@noaa.gov">charles.featherstone@noaa.gov</a>
</p>
<br>
<br>
<cite>Cite as: NOAA Atlantic Oceanographic and Meteorological Laboratories (AOML): Archive of data and information about the former AOML geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5VM498W">doi:10.7289/V5VM498W</a> [access date]<cite> 
<br>
<br>
<p>AOML no longer maintains a core repository/samples are no longer available.</p>', 20150918, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('97', 'OER', 'NOAA Office of Ocean Exploration and Research', 'Samples held at OSU-MGR', '4700 SW Research Way', 'Corvallis, OR 97333', 'USA', 'Joe Stoner, Curator 1 541 737-9002', 'Anthony Koppers, Rock Curator', 'Core Laboratory 1 541 737-8210', 'osu-mgr@oregonstate.edu', 'https://osu-mgr.org/', null, null, '<p><a href=" https://oceanexplorer.noaa.gov/">NOAA Ocean Exploration</a><br>(https://oceanexplorer.noaa.gov/)<br>Through a partnership between NOAA Ocean Exploration and Oregon State University, all geological samples collected during Okeanos Explorer expeditions are archived at the Marine and Geology Repository at Oregon State University. <br><br><a href="https://osu-mgr.org/">Oregon State University Marine and Geology Repository</a><br>(https://osu-mgr.org/)<br>Joe Stoner, Co-Director<br>Anthony Koppers, Co-Director<br>Maziet Cheseby, Curator<br>Cara Fritz, Curator<br>Val Stanley, Curator Antarctic Core Collection<br>Emily Cahoon, Rock Curator<br>College of Earth, Ocean, and Atmospheric Sciences<br>4700 SW Research Way<br>Oregon State University<br>Corvallis, OR 97333<br>(541)737-8210<br><br><a href="mailto:osu-mgr@oregonstate.edu">osu-mgr@oregonstate.edu</a><br></p><br><br><cite>', 20211210, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('67', 'EDYTEM', 'Universite de Savoie, EDYTEM', 'Universite de Savoie, Laboratoire EDYTEM', 'UMR 5204 du CNRS, Batiment Pole Montagne', ' F-73376 LE BOURGET DU LAC Cedex', 'France', 'Cecile Pignol', null, null, 'cecile.pignol@univ-savoie.fr', 'http://edytem.univ-savoie.fr/', null, null, '<p><strong>Environnements, Dynamiques et Territoires de la Montagne (EDYTEM)</strong><br>(<a href="http://edytem.univ-savoie.fr/plateformes-technologiques/plateforme-caracterisation-des-geomateriaux/" title="external link to EDYTEM">http://edytem.univ-savoie.fr/plateformes-technologiques/plateforme-caracterisation-des-geomateriaux/</a>)<br><br>Cecile Pignol<br>Universite de Savoie<br>Laboratoire EDYTEM - UMR 5204 du CNRS<br>Batiment Pole Montagne<br>F-73376 LE BOURGET DU LAC Cedex<br>04 79 75 87 63 (Labo Sedimento)<br><a href="mailto:cecile.pignol@univ-savoie.fr">cecile.pignol@univ-savoie.fr</a><br><br></p><br><br>
<cite>Cite as: Universite de Savoie Laboratoire Environnements, Dynamiques et Territoires de la Montagne (EDYTEM): Archive of information about the EDYTEM geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5416V26">doi:10.7289/V5416V26</a> [date of access]</cite>', 20151027, 'Y', null);
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('06', 'USGSSP', 'St. Petersburg Coastal and Marine Science Center', 'U.S. Geological Survey', '600 Fourth Street South', 'St. Petersburg, FL 33701', 'USA', 'James Flocks 1 727 803-8747 x3012', null, null, 'jflocks@usgs.gov', 'http://coastal.er.usgs.gov/cfcg/', null, null, '<p><a href="http://coastal.er.usgs.gov/cfcg/">U.S. Geological Survey<br>St. Petersburg Coastal and Marine Science Center<br>Marine Sample Repository</a><br>(http://coastal.er.usgs.gov/cfcg/)<br><br>James Flocks<br>U.S. Geological Survey<br>St. Petersburg Coastal and Marine Science Center<br>600 Fourth Street South<br>St. Petersburg, FL 33701<br>(727) 803-8747 x3012<br><a href="mailto:jflocks@usgs.gov">jflocks@usgs.gov</a><br></p><br><br>
<cite>Cite as: U.S. Geological Survey (USGS) Coastal and Marine Geology Program (CMGP) St. Petersburg Coastal and Marine Science Center (SPCMSC): Archive of data and information related to the USGS SPCMSC Samples Repository geoscience collections. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5222RR4">doi:10.7289/V5222RR4</a> [date of access].</cite>', 20151027, 'Y', null);
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('70', 'BPCRC', 'BPCRC Sediment Core Repository', 'Byrd Polar and Climate Research Center', '1090 Carmack Rd', 'Columbus, OH 43210', 'USA', 'Leonid Polyak 1 614 292-2602', null, null, 'polyak.1@osu.edu', '//research.bpcrc.osu.edu/geo/repository.php', null, null, '<p><a href="https://bpcrc.osu.edu/" target="_top">Byrd Polar and Climate Research Center at The Ohio State University</a><br><br><a href="https://research.bpcrc.osu.edu/geo/repository.php" target="_top">Sediment Core Facility, BPCRC</a><br><br>(https://research.bpcrc.osu.edu/geo/repository.php) <br>Leonid Polyak, Curator<br>Sediment Core Facility<br>Byrd Polar and Climate Research Center<br>1090 Carmack Rd.<br>Columbus, OH 43210<br>(614)292-2602<br>(614)292-4697(fax) <br><a href="mailto:polyak.1@osu.edu">polyak.1@osu.edu</a> <br><br><cite>Cite BPCRC sediment cores/data discovered via the IMLGS as: <br>The Ohio State University Byrd Polar and Climate Research Center (BPRC) Sediment Core Repository: Archive of data and information about the BPRC sediment core collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5BP00RZ">doi:10.7289/V5BP00RZ</a> [date of access].</p>', 20220711, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('70', 'BPCRR', 'BPCRC Polar Rock Repository', 'Byrd Polar and Climate Research Center', '108 Scott Hall, 1090 Carmack Rd', 'Columbus, OH 43210', 'USA', 'Anne Grunnow 1 614 292 6531', null, null, 'curator@bprc.mps.ohio-state.edu', 'http://research.bpcrc.osu.edu/rr/', null, null, '<p><a href="https://bpcrc.osu.edu/" target="_top">Byrd Polar and Climate Research Center at The Ohio State University</a><br><br><a href="https://research.bpcrc.osu.edu/rr/" target="_top">Polar Rock Repository, BPCRC</a><br>(https://research.bpcrc.osu.edu/rr/)<br><br>Anne Grunnow, Curator<br>Polar Rock Repository<br>Byrd Polar and Climate Research Center<br>108 Scott Hall<br>1090 Carmack Rd.<br>Columbus, OH 43210<br>(614)292-6531<br><a href="mailto:curator@bprc.mps.ohio-state.edu">curator@bprc.mps.ohio-state.edu</a><br><br><cite>Cite as: The Polar Rock Repository (PRR), Byrd Polar and Climate Research Center (BPCRC), Ohio State University: Geological samples available for research from the PRR. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5RF5S18" title="external link to resolve DOI">doi:10.7289/V5RF5S18</a> [date of access]</cite><br>', 20220711, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('81', 'AWI', 'Alfred Wegener Institut', 'Core Repository', 'Am Alten Hafen 26', '27568  Bremerhaven', 'Germany', 'Hannes Grobe', null, null, 'hgrobe@awi-bremerhaven.de', 'http://www.pangaea.de/search', null, null, '<p><a href="https://www.awi.de/en/science/geosciences/marine-geology/tools/facilities/core-repository.html" target="_top">Alfred-Wegener-Institut (AWI)</a>
<br>(https://www.awi.de/en/science/geosciences/marine-geology/tools/facilities/core-repository.html)
<br>Hannes Grobe
<br>Alfred-Wegener-Institut
 Core Repository
<br>Am Alten Hafen 26 
<br>27568 Bremerhaven, Germany <br><a href="mailto:hgrobe@awi-bremerhaven.de">hgrobe@awi-bremerhaven.de</a>
</p>
<br>
<br>
<cite>Cite as: Alfred-Wegener-Institut (AWI) Core Repository: Archive of information about the AWI geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5NZ85N8">doi:10.7289/V5NZ85N8</a> [date of access].</cite>
<br>
<br>
<p>For complete/updated AWI holdings, see <a href="http://www.pangaea.de">http://www.pangaea.de</a></p>', 20150922, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('10', 'UT', 'Univ of Texas Marine Science Institute', 'Institute for Geophysics', '4412 Spicewood Springs, #600', 'Austin, TX 78759-8500', 'USA', 'Patricia Ganey-Curry 1 512 471-0408', null, null, 'patty@ig.utexas.edu', 'http://www.ig.utexas.edu/', null, null, '<p><a href="http://www.ig.utexas.edu/">University of Texas at Austin Institute for Geophysics</a><br>(http://www.ig.utexas.edu/)<br>Patricia Ganey-Curry<br>University of Texas at Austin Institute for Geophysics<br>4412 Spicewood Springs, #600<br>Austin, TX 78759-8500<br>(512)471-0408<br>(512)471-8844 (fax)<br><a href="mailto:patty@ig.utexas.edu">patty@ig.utexas.edu</a><br></p><br><br>
<cite>Cite as: University of Texas at Austin (UT) Institute of Geophysics: Archive of information about the UT geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5513W54">doi:10.7289/V5513W54</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('06', 'USGSMP', 'USGS Pacific Coastal and Marine Science Center', 'U.S. Geological Survey', '400 Natural Bridges Drive', 'Santa Cruz, CA 95060', 'USA', 'Michael Torresan 831 460-7425 or 650 465-7715', null, null, 'mtorresan@usgs.gov', 'http://walrus.wr.usgs.gov/', null, null, '<p><a href="http://walrus.wr.usgs.gov">U.S. Geological Survey<br>Pacific Coastal and Marine Science Center<br>Marine Sample Repository</a><br>(http://walrus.wr.usgs.gov)<br><br> Mike Torresan<br> U.S. Geological Survey<br> Pacific Coastal and Marine Science Center<br> 400 Natural Bridges Drive<br> Santa Cruz, CA 95060<br> (831)460-7425<br>cell: (650)465-7715<br> <a href="mailto:mtorresan@usgs.gov">mtorresan@usgs.gov</a> <br> </p><br><br>
<cite>Cite as: U.S. Geological Survey (USGS) Coastal and Marine Geology Program (CMGP) Pacific Coastal and Marine Science Center (PCMSC): Archive of data and information related to the USGS PCMSC Samples Repository geoscience collections. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V55T3HGJ">doi:10.7289/V55T3HGJ</a> [date of access].</cite>', 20220711, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('07', 'OSU', 'Oregon State Univ Marine and Geology Repository', 'College of Earth, Ocean, and Atmosph Sciences', '4700 SW Research Way', 'Corvallis, OR 97333', 'USA', 'Joe Stoner, Curator 1 541 737-9002', 'Anthony Koppers, Rock Curator', 'Core Laboratory 1 541 737-8210', 'osu-mgr@oregonstate.edu', 'https://osu-mgr.org/', null, null, '<p><a href="https://osu-mgr.org/">Oregon State University Marine and Geology Repository</a><br>(https://osu-mgr.org/)<br>Joe Stoner, Co-Director<br>Anthony Koppers, Co-Director<br>Maziet Cheseby, Curator<br>Cara Fritz, Curator<br>Val Stanley, Curator Antarctic Core Collection<br>Emily Cahoon, Rock Curator<br>College of Earth, Ocean, and Atmospheric Sciences<br>4700 SW Research Way<br>Oregon State University<br>Corvallis, OR 97333<br>(541)737-8210<br><br><a href="mailto:osu-mgr@oregonstate.edu">osu-mgr@oregonstate.edu</a><br></p><br><br><cite>Cite as: Oregon State University Marine and Geology Repository (OSU-MGR): Archive of OSU geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5TH8JPB">doi:10.7289/V5TH8JPB</a> [date of access]</cite>', 20220217, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('14', 'RSMAS', 'Rosenstiel School of Marine & Atmos. Sciences', 'RSMAS', '4600 Rickenbacker Causeway', 'Miami, FL 33149', 'USA', 'Larry Peterson 1 305 361-4692', null, null, 'lpeterson@rsmas.miami.edu', 'http://www.rsmas.miami.edu/', null, null, '<p><a href="http://www.rsmas.miami.edu/">Rosenstiel School of Marine and Atmospheric Sciences, University of Miami</a><br>(http://www.rsmas.miami.edu/)<br>Larry Peterson<br>Rosenstiel School of Marine<br>and Atmospheric Sciences<br>4600 Rickenbacker Causeway<br>Miami, FL 33149<br>(305)361-4692<br>(305)361-4632 (fax)<br><a href="mailto:lpeterson@rsmas.miami.edu">lpeterson@rsmas.miami.edu</a><br></p><br><br>
<cite>Cite as: Rosenstiel School of Marine and Atmospheric Science (RSMAS) Department of Marine Geosciences: Archive of information about the RSMAS geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5CF9N3M">doi:10.7289/V5CF9N3M</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('15', 'SIO', 'Scripps Institution of Oceanography', 'Geological Collections', '2310 Downwind Way, DSDP Bldg East', 'La Jolla, CA 92037', 'USA', 'Alexandra Hangsterfer, 1 858 822-4837', 'Richard Norris, Curator', 'James Hawkins, Assoc Curator, Rocks', 'ahangsterfer@ucsd.edu', 'http://collections.ucsd.edu/', null, null, '<p><a href="http://collections.ucsd.edu/">Scripps Institution of Oceanography, University of California-San Diego</a><br>(http://collections.ucsd.edu/) <br>Richard Norris, Curator<br>James Hawkins, Assoc Curator, Rocks<br>Alexandra Hangsterfer, Collections Manager<br>Geological Collections <br>Scripps Institution of Oceanography <br>University of California, San Diego <br>2310 Downwind Way<br>Deep Sea Drilling Project East<br>La Jolla, CA 92037<br>(858)822-4837<br><a href="mailto:rnorris@ucsd.edu">rnorris@ucsd.edu</a><br><a href="mailto:jhawkins@ucsd.edu">jhawkins@ucsd.edu</a><br><a href="mailto:ahangsterfer@ucsd.edu">ahangsterfer@ucsd.edu</a> <br></p><br><br>
<cite>Cite as: Scripps Institution of Oceanography (SIO) Geological Collections: Archive of SIO geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V57S7KRR">doi:10.7289/V57S7KRR</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('66', 'USGSWH', 'USGS Woods Hole Coastal and Marine Science Center', 'U.S. Geological Survey', '384 Woods Hole Road', 'Woods Hole, MA 02543', 'USA', 'Brian Buczkowski 1 508 457-2361', null, null, 'gs-wh_curator@usgs.gov', 'http://woodshole.er.usgs.gov/', null, null, '<p><a href="http://woodshole.er.usgs.gov/operations/ia/samprepo/">U.S. Geological Survey<br>Woods Hole Marine Science Center<br>Marine Sample Repository</a><br>(http://woodshole.er.usgs.gov/operations/ia/samprepo/)<br><br>Brian Buczkowski<br>U.S. Geological Survey<br>Woods Hole Coastal and Marine Science Center<br>384 Woods Hole Road<br>Woods Hole, MA 02543<br>Office: (508)457-2361<br>Lab: (508) 457-2287<br><a href="mailto:bbuczkowski@usgs.gov">bbuczkowski@usgs.gov</a><br><a href="mailto:gs-wh_curator@usgs.gov">gs-wh_curator@usgs.gov</a><br></p><br><br>
<cite>Cite as: U.S. Geological Survey (USGS) Coastal and Marine Geology Program (CMGP) Woods Hole Coastal and Marine Science Center (WHCMSC): Archive of data and information related to the USGS WHCMSC Samples Repository geoscience collections. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5X92887">doi:10.7289/V5X92887</a> [date of access].</cite>', 20220711, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('17', 'URI', 'University of Rhode Island', 'Graduate School of Oceanography', 'University of Rhode Island', 'Narragansett Bay Campus', 'Narragansett, RI 02882', 'Steven Carey 1 401 874-6209', null, null, 'mgsl@etal.uri.edu', 'https://web.uri.edu/gso/', null, null, '<p><a href="https://web.uri.edu/gso/research/marine-geological-samples-laboratory/">University of Rhode Island, Graduate School of Oceanography</a><br>(https://web.uri.edu/gso/research/marine-geological-samples-laboratory/) <br> Katherine Kelley, Co-Director <br> Rebecca Robinson, Co-Director <br> Danielle Cares, Curator <br> Graduate School of Oceanography <br> University of Rhode Island <br> Narragansett Bay Campus <br> Narragansett, RI 02882 <br> (401) 874-6838 <br> <a href="mailto:mgsl@etal.uri.edu">mgsl@etal.uri.edu</a> </p><br><br><cite>Cite as: University of Rhode Island (URI) Graduate School of Oceanography (GSO), Marine Geological Samples Laboratory (MGSL): Archive of URI geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5JQ0Z0W">doi:10.7289/V5JQ0Z0W</a> [access date]</cite>', 20220303, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('42', 'U WISC', 'University of Wisconsin-Madison', 'Univ of Wisconsin Geology Museum', '1215 W. Dayton Street', 'Madison, WI 53706', 'USA', 'Carrie Eaton 1 608 262-4912', null, null, 'carrie@geology.wisc.edu', 'http://geology.wisc.edu/', null, null, '<p><a href="http://www.geology.wisc.edu/">University of Wisconsin, Department of Geology and Geophysics</a><br>(http://geology.wisc.edu/)<br>Richard Slaughter<br>Department of Geology and Geophysics<br>University of Wisconsin-Madison<br>A120A Weeks Hall<br>1215 W. Dayton Street<br>Madison, WI 53706<br>(608)262-1412<br>(608)262-0693 (fax)<br><a href="mailto:rich@geology.wisc.edu">rich@geology.wisc.edu</a><br></p><br><br>
<cite>Cite as: University of Wisconsin-Madison Department of Geoscience: Archive of information about the Ice Island T3 piston core collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V51834G7">doi:10.7289/V51834G7</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('02', 'WHOI', 'Woods Hole Oceanographic Institution', 'Dept of Geology and Geophysics', 'Core Laboratory', 'Woods Hole, MA 02543', 'USA', 'Jim Broda 1 508 289-2466', 'Ellen Roosen 1 508 289-2959', null, 'jbroda@whoi.edu', 'http://www.whoi.edu/corelab/', null, null, '<p><a href="http://www.whoi.edu/science/GG/corelab/index.html">Woods Hole Oceanographic Institution</a><br>(http://www.whoi.edu/science/GG/corelab/index.html)<br>Jim Broda<br>Ellen Roosen<br>Woods Hole Oceanographic Institution<br>Department of Geology and Geophysics<br>Woods Hole, MA 02543<br>(508)289-2466 (Jim Broda)<br>(508)289-2959 (Ellen Roosen)<br>(508)457-2183 (fax)<br><a href="mailto:jbroda@whoi.edu">jbroda@whoi.edu</a><br><a href="mailto:eroosen@whoi.edu">eroosen@whoi.edu</a><br></p><br><br>
<cite>Cite as: Woods Hole Oceanographic Institution (WHOI) Seafloor Samples Laboratory: Archive of WHOI geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5WH2N0Z">doi:10.7289/V5WH2N0Z</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('03', 'PMEL', 'NOAA-Pacific Marine Environmental Labs', 'NOAA-PMEL', '2115 SE OSU Dr.', 'Newport, OR 97365-5297', 'USA', 'Stephen Hammond 1 541 867-0183', null, null, 'stephen.r.hammond@noaa.gov', 'http://www.pmel.noaa.gov/', null, null, '<p><a href="http://www.pmel.noaa.gov/">Pacific Meteorological and Environmental Laboratories (PMEL)</a><br>(http://www.pmel.noaa.gov/)<br>Stephen Hammond<br>NOAA - Pacific Meteorological and Environmental Laboratories<br>2115 SE OSU Dr.<br>Newport, OR 97365-5297<br>(541)867-0183<br><a href="mailto:hammond@pmel.noaa.gov">hammond@pmel.noaa.gov</a><br></p><br><br>
<cite>Cite as: NOAA Pacific Marine Environmental Laboratory (PMEL): Archive of information about the PMEL geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V50C4SRS">doi:10.7289/V50C4SRS</a> [date of access]</cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('12', 'Canada', 'Geological Survey of Canada (GSC)', 'National Marine Geoscience Collection', 'Bedford Institute of Oceanography', 'Dartmouth, Nova Scotia B2Y 4A2', 'Canada', 'Kate Jarrett 902 426-6127', null, null, 'kate.jarrett@nrcan-rncan.gc.ca', 'https://ed.gdr.nrcan.gc.ca/index_e.php', null, null, '<p><a href="https://ed.gdr.nrcan.gc.ca/index_e.php">Geological Survey of Canada (GSC) Marine Geoscience Collection (GSC Atlantic and GSC Pacific)</a><br>(https://ed.gdr.nrcan.gc.ca/index_e.php) <br>Kate Jarrett<br> National Marine Geoscience Collection <br> Geological Survey of Canada, Atlantic (GSC Atlantic) <br> Bedford Institute of Oceanography <br> Dartmouth, Nova Scotia <br> Canada <br> B2Y 4A2 <br> (902)426-6127 <br> <a href="mailto:kjarrett@nrcan.gc.ca">kate.jarrett@nrcan-rncan.gc.ca</a> <br> </p><br><br><cite>Cite as: Geological Survey of Canada (GSC) Marine Geoscience Collection (GSC Atlantic and GSC Pacific): Archive of information about the National Marine Geoscience Collection of Canada. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5H70CS1">doi:10.7289/V5H70CS1</a></cite>', 20220422, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('81', 'GEOMAR', 'GEOMAR Helmholtz Centre for Ocean Research Kiel', 'Logistics and Core Repositories', 'Dienstgeb&auml;ude Ostufer', 'Wischhofstr. 1-3, D-24148 Kiel', 'Germany', 'Doris Maicher  49 431 600-2251', null, null, 'dmaicher@geomar.de', 'http://www.geomar.de/en/centre/', null, null, '<p><a href="http://www.geomar.de/en/centre/central-facilities/tlz/lithothek/">GEOMAR Helmholtz Centre for Ocean Research Kiel</a><br>(http://www.geomar.de/en/centre/central-facilities/tlz/lithothek/)
<br>Doris Maicher<br>GEOMAR Helmholtz Centre for Ocean Research Kiel<br>Logistics and Core Repositories<br>Dienstgeb&auml;ude Ostufer<br>Wischhofstr. 1-3<br>24145 Kiel, Germany<br>+49 (0431) 600-2113<br>+49 (0431) 600-1601 (fax)<br><a href="mailto:dmaicher@geomar.de">dmaicher@geomar.de</a><br><br>For complete/updated IFM-GEOMAR holdings, see <a href="http://www.pangaea.de">http://www.pangaea.de</a></p><br><br>
<cite>Cite as: GEOMAR Helmholtz Centre for Ocean Research Kiel Core Repository: Archive of information about the GEOMAR geosample collection. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5J67DXV">doi:10.7289/V5J67DXV</a></cite>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('98', 'IMAGES', 'IMAGES', 'Institute fuer Geowissenschaften', 'Christian-Albrechts-Universitaet', 'Olshausenstrasse 40, D-24098 Kiel', 'Germany', 'Stefan Rothe', 'Data only, no samples at this facility', 'cores are archived elsewhere.', 'sro@gpi.uni-kiel.de', 'http://www.images-pages.org/', null, null, '<br>', 20151027, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('01', 'LDEO', 'Lamont-Doherty Earth Observatory', 'Lamont-Doherty Core Repository, B03 Geosci', 'Columbia University, 61 Route 9W', 'Palisades, NY 10964', 'USA', 'Nichole Anest 1 845 365-8792', null, null, 'curator@ldeo.columbia.edu', 'https://corerepository.ldeo.columbia.edu/', null, null, '<p><a href="https://corerepository.ldeo.columbia.edu/">The Lamont-Doherty Core Repository (LDCR)</a><br>(https://corerepository.ldeo.columbia.edu/)<br>Nichole Anest<br>Curator, Lamont-Doherty Core Repository<br>B03 Geoscience<br>Lamont-Doherty Earth Observatory<br>Columbia University<br>61 Route 9W<br>Palisades, NY 10964<br>(845) 365-8792<br><a href="mailto:corelab@ldeo.columbia.edu">corelab@ldeo.columbia.edu</a></p><br><br><cite>Cite as: Lamont-Doherty Core Repository (LDCR): Archive of LDCR geosample data and information. NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5M61H7G">doi:10.7289/V5M61H7G</a> [date of access]</cite>', 20220505, 'Y', 'Y');
INSERT INTO ${schema_name}.CURATORS_FACILITY (INST_CODE, FACILITY_CODE, FACILITY, ADDR_1, ADDR_2, ADDR_3, ADDR_4, CONTACT_1, CONTACT_2, CONTACT_3, EMAIL_LINK, URL_LINK, FTP_LINK, OTHER_LINK, FACILITY_COMMENT, LAST_UPDATE, PUBLISH, PREVIOUS_STATE) VALUES ('07', 'ACC', 'Antarctic Core Collection, Oregon State University', 'College of Earth, Ocean, and Atmosph Sciences', '4700 SW Research Way', 'Corvallis, OR 97333', 'USA', null, null, null, 'osu-mgr@oregonstate.edu', 'https://osu-mgr.org/', null, null, '<p><a href="https://osu-mgr.org/">Oregon State University Marine and Geology Repository Antarctic Core Collection (OSU-MGR-ACC)</a><br>(https://osu-mgr.org/)<br>Joe Stoner, Co-Director<br>Anthony Koppers, Co-Director<br>Val Stanley, Curator Antarctic Core Collection (POC)<br>Maziet Cheseby, Curator<br>Cara Fritz, Curator<br>Emily Cahoon, Rock Curator<br>College of Earth, Ocean, and Atmospheric Sciences<br>4700 SW Research Way<br>Oregon State University<br>Corvallis, OR 97333<br>(541)737-8210<br><br><a href="mailto:osu-mgr@oregonstate.edu">osu-mgr@oregonstate.edu</a><br></p><br><br><cite>Cite as: Oregon State University Marine and Geology Repository Antarctic Core Collection (OSU-MGR-ACC). 1977: Archive of Geosample Data and Information from the Oregon State University (OSU) College of Earth, Ocean, and Atmospheric Sciences (CEOAS) Marine and Geology Repository (MGR) Antarctic Core Collection (ACC). NOAA National Centers for Environmental Information. <a href="https://dx.doi.org/10.7289/V5RR1W7S">doi:10.7289/V5RR1W7S</a> [date of access]</cite>', 20220204, 'Y', null);
