INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6C', 'sedimentary (organic), limestone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6D', 'sedimentary (organic), limestone, lithographic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6E', 'sedimentary (organic), dolomite/dolostone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6F', 'sedimentary (organic), radiolarites (chert)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6G', 'sedimentary (organic), diatomites (chert)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6H', 'sedimentary (organic), phosphorite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6I', 'sedimentary (organic), iron stone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6J', 'sedimentary (organic), iron ore', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6K', 'sedimentary (organic), coal', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6L', 'sedimentary (organic), peat', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7A', 'metamorphic (metamorphosed), metabasalt/greenstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7B', 'metamorphic (metamorphosed), metadiabase/greenstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7C', 'metamorphic (metamorphosed), metagabbro/greenstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7D', 'metamorphic (metamorphosed), greenstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7E', 'metamorphic (metamorphosed), serpentinite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7F', 'metamorphic (metamorphosed), soapstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7G', 'metamorphic (metamorphosed), rodingite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7H', 'metamorphic (metamorphosed), slate', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7I', 'metamorphic (metamorphosed), phyllite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7J', 'metamorphic (metamorphosed), schist', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7K', 'metamorphic (metamorphosed), gneiss', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7L', 'metamorphic (metamorphosed), gneiss, banded', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7M', 'metamorphic (metamorphosed), gneiss, augen', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7N', 'metamorphic (metamorphosed), quartzite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7O', 'metamorphic (metamorphosed), marble', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7P', 'metamorphic (metamorphosed), eclogite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7Q', 'metamorphic (metamorphosed), granulite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7R', 'metamorphic (metamorphosed), migmatite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7S', 'metamorphic (metamorphosed), hornfels', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7T', 'metamorphic (metamorphosed), skarn', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7U', 'metamorphic (metamorphosed), amphibolite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7V', 'metamorphic (metamorphosed), blastomylonite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7W', 'metamorphic (metamorphosed), ultramylonite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7X', 'metamorphic (metamorphosed), cataclastite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7Y', 'metamorphic (metamorphosed), tectonite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8A', 'sediments (unconsolidated), clay, unfossiliferous', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8B', 'sediments (unconsolidated), clay, calcareous (1-30% biogenous matter-calcareous)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8C', 'sediments (unconsolidated), ooze, calcareous (>30% biogenous matter)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8D', 'sediments (unconsolidated), clay, siliceous (1-30% biogenous matter-siliceous)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8E', 'sediments (unconsolidated), ooze, siliceous (>30% biogenous matter)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8F', 'sediments (unconsolidated), ooze, calcareous-siliceous', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8G', 'sediments (unconsolidated), sand, calcareous (forams/pteropods)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8H', 'sediments (unconsolidated), shell/coral hash', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8I', 'sediments (unconsolidated), lutite (unconsolidated)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8J', 'sediments (unconsolidated), silt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8K', 'sediments (unconsolidated), sand', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8L', 'sediments (unconsolidated), gravel', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8M', 'sediments (unconsolidated), glacial erratics', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8N', 'sediments (unconsolidated), coral', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8O', 'sediments (unconsolidated), sponge', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8P', 'sediments (unconsolidated), shell fragments (tests)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8Q', 'sediments (unconsolidated), vent clams', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8R', 'sediments (unconsolidated), vent worm tests', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8S', 'sediments (unconsolidated), crabs (+/- vent origin)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8T', 'sediments (unconsolidated), urchins', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8U', 'sediments (unconsolidated), sea cucumbers', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0', 'igneous (intrusive/plutonic)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1', 'igneous (hypabyssal)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2', 'igneous (extrusive/volcanic)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3', 'sedimentary (pyroclastic)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4', 'sedimentary (detrital/fragmental or clastic)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5', 'sedimentary (chemical)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6', 'sedimentary (organic)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('7', 'metamorphic (metamorphosed)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('8', 'sediments (unconsolidated)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5A', 'sedimentary (chemical), chert/porcelanite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0A', 'igneous (intrusive/plutonic), gabbro', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0B', 'igneous (intrusive/plutonic), gabbro, olivine', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0C', 'igneous (intrusive/plutonic), gabbro, quartz', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0D', 'igneous (intrusive/plutonic), gabbro, ferro', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0E', 'igneous (intrusive/plutonic), anorthosite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0F', 'igneous (intrusive/plutonic), troctolite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0G', 'igneous (intrusive/plutonic), norite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0H', 'igneous (intrusive/plutonic), metagabbro', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0I', 'igneous (intrusive/plutonic), peridotite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0J', 'igneous (intrusive/plutonic), dunite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0K', 'igneous (intrusive/plutonic), harzburgite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0L', 'igneous (intrusive/plutonic), wehrlite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0M', 'igneous (intrusive/plutonic), lherzolite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0N', 'igneous (intrusive/plutonic), pyroxenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0O', 'igneous (intrusive/plutonic), hornblendite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0P', 'igneous (intrusive/plutonic), websterite, olivine', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0Q', 'igneous (intrusive/plutonic), clinopyroxenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0R', 'igneous (intrusive/plutonic), orthopyroxenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0S', 'igneous (intrusive/plutonic), serpentinite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0T', 'igneous (intrusive/plutonic), granite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0U', 'igneous (intrusive/plutonic), granodiorite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0V', 'igneous (intrusive/plutonic), tonalite (qtz diorite)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0W', 'igneous (intrusive/plutonic), tondhjemite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0X', 'igneous (intrusive/plutonic), diorite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0Y', 'igneous (intrusive/plutonic), monzonite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('0Z', 'igneous (intrusive/plutonic), syenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1A', 'igneous (hypabyssal), diabase', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1B', 'igneous (hypabyssal), diabase, aphyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1C', 'igneous (hypabyssal), diabase, olivine phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1D', 'igneous (hypabyssal), diabase, plagioclase phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1E', 'igneous (hypabyssal), diabase, ol-pg phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1F', 'igneous (hypabyssal), diabase, ol-pg-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1G', 'igneous (hypabyssal), diabase, pg-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1H', 'igneous (hypabyssal), diabase, ol-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1I', 'igneous (hypabyssal), diabase, cpx-phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1J', 'igneous (hypabyssal), metadiabase', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1K', 'igneous (hypabyssal), granite porphyry', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1L', 'igneous (hypabyssal), granophyre', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1M', 'igneous (hypabyssal), diorite porphyry', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1N', 'igneous (hypabyssal), pegmatite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1O', 'igneous (hypabyssal), lamprophyre', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('1P', 'igneous (hypabyssal), aplite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2A', 'igneous (extrusive/volcanic), basalt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2B', 'igneous (extrusive/volcanic), basalt, aphyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2C', 'igneous (extrusive/volcanic), basalt, olivine phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2D', 'igneous (extrusive/volcanic), basalt, plagioclase phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2E', 'igneous (extrusive/volcanic), basalt, ol-pg phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2F', 'igneous (extrusive/volcanic), basalt, ol-pg-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2G', 'igneous (extrusive/volcanic), basalt, pg-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2H', 'igneous (extrusive/volcanic), basalt, ol-cpx phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2I', 'igneous (extrusive/volcanic), basalt, clinopyroxene phyric', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2J', 'igneous (extrusive/volcanic), basalt, pillow', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2K', 'igneous (extrusive/volcanic), basalt, vesicular (>10% vesicles)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2L', 'igneous (extrusive/volcanic), pumice/scoria', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2M', 'igneous (extrusive/volcanic), hyaloclastites', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2N', 'igneous (extrusive/volcanic), obsidian/quenched basalt-glass', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2O', 'igneous (extrusive/volcanic), metabasalt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2P', 'igneous (extrusive/volcanic), andesites', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2Q', 'igneous (extrusive/volcanic), dacites', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2R', 'igneous (extrusive/volcanic), rhyolite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2S', 'igneous (extrusive/volcanic), trachyte', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2T', 'igneous (extrusive/volcanic), latite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2U', 'igneous (extrusive/volcanic), phonolite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2V', 'igneous (extrusive/volcanic), trachybasalt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2W', 'igneous (extrusive/volcanic), tephrite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2X', 'igneous (extrusive/volcanic), nephelinite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2Y', 'igneous (extrusive/volcanic), leucitite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2Z', 'igneous (extrusive/volcanic), basanite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('2*', 'igneous (extrusive/volcanic), sheet flow basalt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3A', 'sedimentary (pyroclastic), tuff', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3B', 'sedimentary (pyroclastic), tuff, vitric (glass clasts)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3C', 'sedimentary (pyroclastic), tuff, crystal (crystal clasts)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3D', 'sedimentary (pyroclastic), tuff, lithic (rock clasts)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3E', 'sedimentary (pyroclastic), tuff, ash (<4mm diam. clasts)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3G', 'sedimentary (pyroclastic), agglomerates (bombs)(>32mm diam)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3H', 'sedimentary (pyroclastic), volcanic breccia (blocks)(>32mm)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3I', 'sedimentary (pyroclastic), hyaloclastite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3J', 'sedimentary (pyroclastic), loose glass fragments', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('3K', 'sedimentary (pyroclastic), breccia, pillow', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4A', 'sedimentary (detrital/fragmental or clastic), conglomerate', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4B', 'sedimentary (detrital/fragmental or clastic), oligomictic conglomerate (clasts of one lithology)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4C', 'sedimentary (detrital/fragmental or clastic), polymictic conglomerate (variable clast lithology)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4D', 'sedimentary (detrital/fragmental or clastic), tillite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4E', 'sedimentary (detrital/fragmental or clastic), breccia', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4F', 'sedimentary (detrital/fragmental or clastic), breccia, hyaloclastite/palagonite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4G', 'sedimentary (detrital/fragmental or clastic), breccia, serpentinite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4H', 'sedimentary (detrital/fragmental or clastic), breccia, intraformational (sed rocks in same matrix)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4I', 'sedimentary (detrital/fragmental or clastic), breccia, tectonic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4J', 'sedimentary (detrital/fragmental or clastic), sandstone/arenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4K', 'sedimentary (detrital/fragmental or clastic), orthoquartzite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4L', 'sedimentary (detrital/fragmental or clastic), sandstone, lithic (containing rock fragments)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4M', 'sedimentary (detrital/fragmental or clastic), arkose', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4N', 'sedimentary (detrital/fragmental or clastic), greywacke', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4O', 'sedimentary (detrital/fragmental or clastic), greywacke, arkosic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4P', 'sedimentary (detrital/fragmental or clastic), greywacke, lithic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4Q', 'sedimentary (detrital/fragmental or clastic), greywacke, volcanic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4R', 'sedimentary (detrital/fragmental or clastic), greywacke, sandy', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4S', 'sedimentary (detrital/fragmental or clastic), shale', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4T', 'sedimentary (detrital/fragmental or clastic), claystone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4U', 'sedimentary (detrital/fragmental or clastic), siltstone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4V', 'sedimentary (detrital/fragmental or clastic), mudstone (lutite)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4W', 'sedimentary (detrital/fragmental or clastic), marl', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4X', 'sedimentary (detrital/fragmental or clastic), calcarenite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4Y', 'sedimentary (detrital/fragmental or clastic), calcilutite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('4Z', 'sedimentary (detrital/fragmental or clastic), calcirudite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5B', 'sedimentary (chemical), jasper', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5C', 'sedimentary (chemical), salt', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5D', 'sedimentary (chemical), gypsum', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5E', 'sedimentary (chemical), anhydrite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5F', 'sedimentary (chemical), limestone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5G', 'sedimentary (chemical), limestone, lithographic', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5H', 'sedimentary (chemical), travertine', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5I', 'sedimentary (chemical), dolomite/dolostone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5J', 'sedimentary (chemical), Mn/Fe oxide crusts and nodules', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5K', 'sedimentary (chemical), Mn/Fe nodules', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5L', 'sedimentary (chemical), phosphorite crusts', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5M', 'sedimentary (chemical), phosphorite nodules', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5N', 'sedimentary (chemical), iron stone', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5O', 'sedimentary (chemical), iron ore', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5P', 'sedimentary (chemical), sulfide chimney (whole specimen)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5Q', 'sedimentary (chemical), sulfide chimney (fragment)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5R', 'sedimentary (chemical), sulfide "dust"', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5S', 'sedimentary (chemical), pyrite/marcasite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5T', 'sedimentary (chemical), chalcopyrite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5U', 'sedimentary (chemical), sphalerite/wurtzite', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5V', 'sedimentary (chemical), calcite (assoc with sulfide chimney)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('5W', 'sedimentary (chemical), amorphous silica (tube worm tests)', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6A', 'sedimentary (organic), chalk', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_ROCK_LITH (ROCK_LITH_CODE, ROCK_LITH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('6B', 'sedimentary (organic), coquina (fossiliferous limestone)', 'Y', 'Y', null);
