INSERT INTO ${schema_name}.CURATORS_STORAGE_METH (STORAGE_METH_CODE, STORAGE_METH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('A', 'frozen', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_STORAGE_METH (STORAGE_METH_CODE, STORAGE_METH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('B', 'refrigerated', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_STORAGE_METH (STORAGE_METH_CODE, STORAGE_METH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('C', 'room temperature, moisture sealed', 'Y', 'Y', null);
INSERT INTO ${schema_name}.CURATORS_STORAGE_METH (STORAGE_METH_CODE, STORAGE_METH, PUBLISH, PREVIOUS_STATE, SOURCE_URI) VALUES ('D', 'room temperature, dry', 'Y', 'Y', null);
