UPDATE ${schema_name}.CURATORS_SAMPLE_TSQP
SET SHOW_SAMPL = REPLACE(SHOW_SAMPL, 'www.ngdc.noaa.gov/geosamples/showsample.jsp?', 'maps.ngdc.noaa.gov/viewers/imlgs/samples/')
WHERE regexp_like(SHOW_SAMPL, '^http');

ALTER TABLE ${schema_name}.CURATORS_FACILITY MODIFY FACILITY varchar(100);
ALTER TABLE ${schema_name}.CURATORS_FACILITY MODIFY ADDR_1 varchar(100);
ALTER TABLE ${schema_name}.CURATORS_FACILITY RENAME COLUMN OTHER_LINK TO DOI_LINK;
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5RR1W7S' WHERE FACILITY_CODE = 'ACC';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5VM498W' WHERE FACILITY_CODE = 'AOML';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5NZ85N8' WHERE FACILITY_CODE = 'AWI';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5N014HR' WHERE FACILITY_CODE = 'BOSCORF';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5BP00RZ' WHERE FACILITY_CODE = 'BPCRC';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/10.7289/V5RF5S18' WHERE FACILITY_CODE = 'BPCRR';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5H70CS1' WHERE FACILITY_CODE = 'Canada';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V57M05XN' WHERE FACILITY_CODE = 'DSDP ';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5GF0RG9' WHERE FACILITY_CODE = 'ECS';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5416V26' WHERE FACILITY_CODE = 'France';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5J67DXV' WHERE FACILITY_CODE = 'GEOMAR';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V57M05XN' WHERE FACILITY_CODE = 'IODP';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'http://dx.doi.org/doi:10.7289/V5M61H7G' WHERE FACILITY_CODE = 'LDEO';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5G73BP3' WHERE FACILITY_CODE = 'LacCore';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5J38QHJ' WHERE FACILITY_CODE = 'NMNH';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V57M05XN' WHERE FACILITY_CODE = 'ODP';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5TH8JPB' WHERE FACILITY_CODE = 'OSU';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V50C4SRS' WHERE FACILITY_CODE = 'PMEL';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5CF9N3M' WHERE FACILITY_CODE = 'RSMAS';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V57S7KRR' WHERE FACILITY_CODE = 'SIO';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V50P0X05' WHERE FACILITY_CODE = 'SOEST';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V51834G7' WHERE FACILITY_CODE = 'U WISC';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5JQ0Z0W' WHERE FACILITY_CODE = 'URI';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V58P5XH8' WHERE FACILITY_CODE = 'USC';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V55T3HGJ' WHERE FACILITY_CODE = 'USGSMP';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5222RR4' WHERE FACILITY_CODE = 'USGSSP';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5X92887' WHERE FACILITY_CODE = 'USGSWH';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5513W54' WHERE FACILITY_CODE = 'UT';
UPDATE ${schema_name}.CURATORS_FACILITY SET DOI_LINK = 'https://dx.doi.org/doi:10.7289/V5WH2N0Z' WHERE FACILITY_CODE = 'WHOI';

UPDATE ${schema_name}.CURATORS_SAMPLE_TSQP SET OTHER_LINK = null;






