insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_SAMPLE_READ');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_SAMPLE_CREATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_SAMPLE_UPDATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_SAMPLE_DELETE');

insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_CRUISE_READ');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_CRUISE_CREATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_CRUISE_UPDATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_CRUISE_DELETE');

insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_INTERVAL_READ');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_INTERVAL_CREATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_INTERVAL_UPDATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_INTERVAL_DELETE');

insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_PLATFORM_READ');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_PLATFORM_CREATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_PLATFORM_UPDATE');
insert into ${schema_name}.GEOSAMPLES_AUTHORITY (AUTHORITY_NAME) values ('ROLE_PROVIDER_PLATFORM_DELETE');